# Generated by Django 2.2.5 on 2019-09-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='full_description',
            field=models.TextField(max_length=600, null=True),
        ),
    ]
